<?php

/**
 * @file
 * Provide Leaflet API integration and field formatters.
 */

module_load_include('inc', 'leaflet', 'leaflet.formatters');

/**
 * Implements hook_theme().
 */
function leaflet_theme($existing, $type, $theme, $path) {
  return array(
    'leaflet_map' => array(
      'variables' => array(
        'map_id' => NULL,
        'height' => '400px',
        'map' => 'OSM Mapnik',
        'map_info' => array(),
        'features' => array(),
      ),
    ),
  );
}

/**
 * Theme pre-processing - adds the necessary JS.
 */
function leaflet_preprocess_leaflet_map(&$vars) {
  if (!empty($vars['map_info'])) {
    $map_info = $vars['map_info'];
  }
  elseif (!empty($vars['map'])) {
    $map_info = leaflet_map_get_info($vars['map']);
  }
  else {
    // @TODO: warning of some sort.
  }
  $settings = leaflet_map_prebuild($vars['map_id'], $map_info, $vars['features']);

  // Load the leaflet library, which includes integration files.
  libraries_load('leaflet');

  drupal_add_css(drupal_get_path('module', 'leaflet') . '/leaflet_extras.css');
  drupal_add_js(array('leaflet' => array($settings)), 'setting');
}

/**
 * Theme function for leaflet map.
 */
function theme_leaflet_map($vars) {
  $build = array(
    '#theme' => 'html_tag',
    '#tag' => 'div',
    '#value' => '',
    '#attributes' => array(
      'id' => $vars['map_id'],
      'style' => 'height: ' . $vars['height'],
    ),
  );
  return render($build);
}

/**
 * Attach Leaflet-required client files and return renderable array for a map.
 *
 * @param array $map
 *   Map definition as returned my leaflet_map_get_info();
 * @param array $features
 *   Associative array of map features.
 * @param string $height
 *   The height of the map.
 * @param string $map_id
 *   The map id to use. If provided it's up to the callee to ensure a valid and
 *   unique html id.
 *
 * @return array
 *   A renderable array.
 */
function leaflet_build_map($map, $features = array(), $height = '400px', $map_id = NULL) {
  // Ensure we've got an unique id.
  if (empty($map_id)) {
    $map_id = drupal_html_id('leaflet_map');
  }
  $build = array(
    '#theme' => 'leaflet_map',
    '#map_id' => $map_id,
    '#map_info' => $map,
    '#height ' => $height,
    '#features' => $features,
  );
  return $build;
}

/**
 * Set settings for a map id.
 *
 * Manages a static cache with the map settings.
 * If the settings parameter is given the settings are set - otherwise existing
 * settings are returned by reference.
 * If settings for a map id already exists and the settings parameter is set the
 * settings are merged using drupal_array_merge_deep(). The settings parameter
 * has priority over the already defined settings.
 *
 * @param string $map_id
 *   Unique identifier for a map.
 * @param array $settings
 *   Settings array as produced by leaflet_map_prebuild().
 *
 * @return array
 *   The settings array by reference(!)
 */
function &leaflet_map_settings($map_id, $settings = array()) {
  $all_settings = &drupal_static(__FUNCTION__, array());
  if (!isset($all_settings[$map_id])) {
    $all_settings[$map_id] = array();
  }
  if (!empty($settings)) {
    $all_settings[$map_id] = drupal_array_merge_deep($all_settings[$map_id], $settings);
  }
  return $all_settings[$map_id];
}

/**
 * Pre-build drupal leaflet JS settings.
 *
 * @param string $map_id
 *   The map id.
 * @param array $map
 *   Map definition as returned my leaflet_map_get_info();
 * @param array $features
 *   Associative array of map features.
 *
 * @return array
 *   An array ready to be used as drupal leaflet JS settings.
 */
function leaflet_map_prebuild($map_id, $map, $features) {
  // Allow map definitions to provide a default icon:
  if (isset($map['icon']['iconUrl'])) {
    foreach ($features as &$feature) {
      if (!isset($feature['icon'])) {
        $feature['icon'] = $map['icon'];
      }
    }
  }

  $settings = leaflet_map_settings($map_id, array(
    'mapId' => $map_id,
    'map' => $map,
    'features' => $features,
  ));
  drupal_alter('leaflet_map_prebuild', $settings);

  return $settings;
}

/**
 * Implements hook_libraries_info().
 */
function leaflet_libraries_info() {
  $libraries['leaflet'] = array(
    // Only used in administrative UI of Libraries API.
    'name' => 'Leaflet JavaScript Library',
    'vendor url' => 'http://leafletjs.com/',
    'download url' => 'http://leaflet-cdn.s3.amazonaws.com/build/leaflet-0.7.1.zip',
    // .7: version="0.7"
    'version arguments' => array(
      'file' => 'leaflet.js',
      'pattern' => '/version="([\d+\.]*\d+)"/',
    ),
    'files' => array(
      'js' => array(
        // This setting is needed in order to properly render market images.
        'leaflet_root_url' => array(
          'type' => 'inline',
          'data' => 'L_ROOT_URL = "' . base_path() . libraries_get_path('leaflet') . '/";',
          'group' => JS_LIBRARY,
          'preprocess' => FALSE,
        ),
        'leaflet.js' => array(
          'type' => 'file',
          'group' => JS_LIBRARY,
          'preprocess' => FALSE,
        ),
      ),
      'css' => array(
        'leaflet.css' => array(
          'type' => 'file',
          'media' => 'all',
        ),
        'leaflet.ie.css' => array(
          'browsers' => array(
            'IE' => 'lte IE 8',
            '!IE' => FALSE,
          ),
        ),
      ),
    ),
    'integration files' => array(
      'leaflet' => array(
        'js' => array('leaflet.drupal.js'),
      ),
    ),
  );

  return $libraries;
}

/**
 * DEPRECATED. Use leaflet_build_map() instead.
 *
 * Load all Leaflet required client files and return markup for a map.
 *
 * @param array $map
 *   Map definition as returned my leaflet_map_get_info();
 * @param array $features
 *   Associative array of map features.
 * @param string $height
 *   The height of the map.
 *
 * @return string
 *   map markup
 */
function leaflet_render_map($map, $features = array(), $height = '400px') {
  $build = leaflet_build_map($map, $features, $height);
  return render($build);
}

/**
 * Get all available Leaflet map definitions.
 *
 * @string $map
 *   The name of the map defined in hook_leaflet_map_get_info().
 */
function leaflet_map_get_info($map = NULL) {
  static $drupal_static_fast;
  if (!isset($drupal_static_fast)) {
    $drupal_static_fast['leaflet_map_info'] = &drupal_static(__FUNCTION__);
  }
  $map_info = &$drupal_static_fast['leaflet_map_info'];

  if (empty($map_info)) {
    if ($cache = cache_get("leaflet_map_info")) {
      $map_info = $cache->data;
    }
    else {
      $map_info = module_invoke_all('leaflet_map_info');

      // Let other modules alter the map info.
      drupal_alter('leaflet_map_info', $map_info);

      cache_set("leaflet_map_info", $map_info);
    }
  }

  if (empty($map)) {
    return $map_info;
  }
  elseif (isset($map_info[$map])) {
    return $map_info[$map];
  }
}

/**
 * Implements hook_leaflet_map_info().
 *
 * Return a default map for the module.
 */
function leaflet_leaflet_map_info() {
  return array(
    'OSM Mapnik' =>
      array(
        'label' => 'OSM Mapnik',
        'description' => t('Leaflet default map.'),
        // Center is used when the map contains no items, or every time the map
        // is loaded if "force" is TRUE. Otherwise, the map will center itself
        // intelligently based on the features in the map.
        // RdB: bad things happen when 'center' is specified and Leaflet
        // MarkerCluster is used, see https://drupal.org/node/2144935
        // Also, a hard-coded center is not a great idea.
        //'center' => array(
        //  'lat' => 45.526513,
        //  'lon' => -122.674833,
        //  'force' => FALSE,
        //),
        'settings' => array(
          // Setting "zoom" forces a zoom level on every map load.
          //'zoom' => 17,
          // The "zoomDefault" is only used when no features are present.
          'zoomDefault' => 10,
          'minZoom' => 0,
          'maxZoom' => 18,
          'dragging' => TRUE,
          'touchZoom' => TRUE,
          'scrollWheelZoom' => TRUE,
          'doubleClickZoom' => TRUE,
          'zoomControl' => TRUE,
          'attributionControl' => TRUE,
          'trackResize' => TRUE,
          'fadeAnimation' => TRUE,
          'zoomAnimation' => TRUE,
          'closePopupOnClick' => TRUE,
        ),
        'layers' => array(
          'earth' => array(
            'urlTemplate' => 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
            'options' => array(
              'attribution' => 'OSM Mapnik',
            ),
          ),
        ),
      ),
  );
}
